### ISSUE TITLE
Example for transfer accept

### ISSUE THREAD

**Issue by cryptoquick** [LNP-BP/nodes#13]
Currently in the demo script, the BLINDING factor on the other machine isn't used, nor is any form of accept transfer command is called (on the other machine). It would help to have an example of how this is done.

**Comment by cryptoquick** [comment]
According to @crisdut, this is what's needed in the example:

The blinding factor is used to reveal Blinded UTXO in consignment file with rgb-cli transfer consume method.

For example:

` rgb-cli transfer consume ./consignment.rgbc --reveal "tapret1st@$receive_txid:$receive_vout#$blind_factor"`

**Comment by crisdut** [comment]
I add more information in `rgb-demo.sh`.

https://github.com/LNP-BP/nodes/pull/14
