### ISSUE TITLE
payload data are not strictly encoded

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/nodes#3]
Following the steps I stuck in the registration step of a contract.

I have the command:
rgb-cli -n testnet contract register rgbc1qxz4y02gr3q3flnxvuh6ufyczx9ngcsk3vzd9fstcjzr8cggyyvvydfps3c85z6exq0xz3ess5jgffqta9pqc5dc70qv9slnlj53g2mdgjc9qsgyrvduzhcs0ugpr4mekwac5g8v9neum7lmm6dhn7cshux9s68fjjhhxm58x3srpxzgw7u4jgyjrzz26gedstdrx3kqfymdttkt90sptqs3gkuucdd2c2g9qf572ag9q7cs9qgj6q22re74egafx9ljzsmtsrh3wdqwdg96625dg9rdlfunljqpq085q3k8af22vszlyg42zwwtana0442pp5rh5cuq8qd4zna04pvf3tmge6qv5wdrj9nx94wecst52yjv9zn3rs3hc4wycsm7s9j7m7xe99hrlnapw4lwwn6semrqwh4d0hxfena0pa7ln8jd8akx55nne6ek0n5da7kf7q8u6ta79c0al7lnmyaz3hj7nx0junmul94llk9gr93fkrats0ryh3unrk8tck2mt4jk43vqdnk5hadxaqrdhtq7dq6g9g2jaejt47gk6g4vsn46kfx5639g0yvenue7hfvrhfpe3zks435z08vntu0vlx43v6kndcxaafyjwmt0n99nxw0wwjy6y9vrgdm4gkcasj35dgup0am38ykc4j2cgddk07tdl0ymkjd8487dscnmg7vlrlv9gl7jlx6wh5rjka7lm7sf0l9087wtq7nxhv3hdnrz2l2hx3hy39c

Which gives as result:

error: Invalid value "rgbc1qxz4y02gr3q3flnxvuh6ufyczx9ngcsk3vzd9fstcjzr8cggyyvvydfps3c85z6exq0xz3ess5jgffqta9pqc5dc70qv9slnlj53g2mdgjc9qsgyrvduzhcs0ugpr4mekwac5g8v9neum7lmm6dhn7cshux9s68fjjhhxm58x3srpxzgw7u4jgyjrzz26gedstdrx3kqfymdttkt90sptqs3gkuucdd2c2g9qf572ag9q7cs9qgj6q22re74egafx9ljzsmtsrh3wdqwdg96625dg9rdlfunljqpq085q3k8af22vszlyg42zwwtana0442pp5rh5cuq8qd4zna04pvf3tmge6qv5wdrj9nx94wecst52yjv9zn3rs3hc4wycsm7s9j7m7xe99hrlnapw4lwwn6semrqwh4d0hxfena0pa7ln8jd8akx55nne6ek0n5da7kf7q8u6ta79c0al7lnmyaz3hj7nx0junmul94llk9gr93fkrats0ryh3unrk8tck2mt4jk43vqdnk5hadxaqrdhtq7dq6g9g2jaejt47gk6g4vsn46kfx5639g0yvenue7hfvrhfpe3zks435z08vntu0vlx43v6kndcxaafyjwmt0n99nxw0wwjy6y9vrgdm4gkcasj35dgup0am38ykc4j2cgddk07tdl0ymkjd8487dscnmg7vlrlv9gl7jlx6wh5rjka7lm7sf0l9087wtq7nxhv3hdnrz2l2hx3hy39c" for '<CONTRACT>': payload data are not strictly encoded - An unsupported value `TypeRef` for enum `TypeRef` encountered during decode operation

Any idea what goes wrong here?

**Comment by crisdut** [comment]
Hi @Goosie,

I believe this issue can help you https://github.com/RGB-WG/rgb-node/issues/189

**Comment by dr-orlovsky** [comment]
Yes, seems you are using non-latest version and there is encoding incompatibility between the versions. Please let me know whether the issue is resolved

**Comment by Goosie** [comment]
> 

Yess solved
