### ISSUE TITLE
Unable to run RGB Demo

### ISSUE THREAD

**Issue by Sudz24** [LNP-BP/nodes#8]
Hi, 

I tried installing the latest packages as mentioned in the demo-rgb.sh, however I get this error while trying to use the installed CLI.

'rgb20 binary not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }'

Can you help me understand why this is happening? I can see the binaries under /.cargo/bin but maybe it's not installed correctly?

Thank you

**Comment by zoedberg** [comment]
the issue is related to the usage of `bindeps`, as already discussed [here](https://github.com/LNP-BP/nodes/discussions/2). using the instructions from https://github.com/LNP-BP/nodes/pull/4 should solve your issue

**Comment by dr-orlovsky** [comment]
Closing as duplicate of #4
